#ifndef VERSION_H
#define VERSION_H

#define XSPRESS_DETECTOR_VERSION_MAJOR 1
#define XSPRESS_DETECTOR_VERSION_MINOR 0
#define XSPRESS_DETECTOR_VERSION_PATCH 0
#define XSPRESS_DETECTOR_VERSION_STR_SHORT "1.0.0"
#define XSPRESS_DETECTOR_VERSION_STR "-128-NOTFOUND"

#endif //VERSION_H
